//! The `oms.toml` bootstrap file.
//!
//! Holds the settings that cannot live in the database, because they are what
//! tells the process how to reach it — plus the master key, which must not live
//! in the thing it encrypts. Everything else belongs in Postgres and is managed
//! from the cockpit.
//!
//! Every field is optional. The file is one tier in the flag → env → file →
//! default chain, so a half-filled file is normal rather than an error.

use std::path::PathBuf;
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

/// Where the file lives when `--config`/`OMS_CONFIG` say nothing.
pub const DEFAULT_FILENAME: &str = "oms.toml";

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FileConfig {
    #[serde(default)]
    pub database: DatabaseSection,
    #[serde(default)]
    pub oms: OmsSection,
    #[serde(default)]
    pub server: ServerSection,
}

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct DatabaseSection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port: Option<u16>,
    /// Superuser *name* only. Its password is prompted, never stored — that
    /// credential can drop the database.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub database: Option<String>,
}

#[derive(Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct OmsSection {
    /// Password for the `oms` role the server connects as. Generated by `oms init`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// `base64:`-prefixed 32 bytes. Losing this loses every stored credential.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub master_key: Option<String>,
}

#[derive(Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ServerSection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bind_addr: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub admin_password: Option<String>,
}

// Hand-written so a stray `{:?}` — in a log line, a panic message, an
// `expect_err` — cannot print the master key or either password. `FileConfig`
// derives Debug and contains these, so deriving here would leak through it.
impl std::fmt::Debug for OmsSection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OmsSection")
            .field("password", &self.password.as_ref().map(|_| "<redacted>"))
            .field("master_key", &self.master_key.as_ref().map(|_| "<redacted>"))
            .finish()
    }
}

impl std::fmt::Debug for ServerSection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ServerSection")
            .field("bind_addr", &self.bind_addr)
            .field("admin_password", &self.admin_password.as_ref().map(|_| "<redacted>"))
            .finish()
    }
}

#[derive(Debug)]
pub enum ConfigError {
    Parse(String),
    Io(String),
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::Parse(m) => write!(f, "{m}"),
            ConfigError::Io(m) => write!(f, "{m}"),
        }
    }
}

impl std::error::Error for ConfigError {}

pub fn parse(toml_str: &str) -> Result<FileConfig, ConfigError> {
    toml::from_str(toml_str).map_err(|e| ConfigError::Parse(e.to_string()))
}

/// The configured path: `--config` is threaded in as `OMS_CONFIG` by `main`, so
/// this single function serves both.
pub fn path() -> PathBuf {
    std::env::var("OMS_CONFIG")
        .ok()
        .filter(|v| !v.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(DEFAULT_FILENAME))
}

static LOADED: OnceLock<Option<FileConfig>> = OnceLock::new();

/// Read and cache the file. Absent is `None` — running without one is valid.
///
/// A file that exists but does not parse is fatal: it means the operator wrote
/// something they believe is in effect. Silently ignoring it could point the
/// server at a different database than they intended.
pub fn load() -> Option<&'static FileConfig> {
    LOADED
        .get_or_init(|| {
            let p = path();
            match std::fs::read_to_string(&p) {
                Err(_) => None,
                Ok(text) => match parse(&text) {
                    Ok(cfg) => Some(cfg),
                    Err(e) => {
                        eprintln!("error: {} is not valid: {e}", p.display());
                        std::process::exit(1);
                    }
                },
            }
        })
        .as_ref()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every field is optional: a partial file must parse, because the missing
    /// pieces fall through to env or the built-in defaults.
    #[test]
    fn parses_a_partial_file() {
        let cfg = parse("[database]\nhost = \"db.internal\"\n").expect("parse");
        assert_eq!(cfg.database.host.as_deref(), Some("db.internal"));
        assert_eq!(cfg.database.port, None);
        assert_eq!(cfg.oms.password, None);
    }

    /// An entirely empty file is legal and yields all-None.
    #[test]
    fn parses_an_empty_file() {
        let cfg = parse("").expect("parse");
        assert_eq!(cfg.database.host, None);
        assert_eq!(cfg.server.bind_addr, None);
    }

    #[test]
    fn parses_a_full_file() {
        let cfg = parse(
            r#"
[database]
host = "localhost"
port = 5432
username = "postgres"
database = "ods"

[oms]
password = "role-pw"
master_key = "base64:AAAA"

[server]
bind_addr = "0.0.0.0:3001"
admin_password = "admin-pw"
"#,
        )
        .expect("parse");
        assert_eq!(cfg.database.port, Some(5432));
        assert_eq!(cfg.oms.master_key.as_deref(), Some("base64:AAAA"));
        assert_eq!(cfg.server.bind_addr.as_deref(), Some("0.0.0.0:3001"));
        assert_eq!(cfg.server.admin_password.as_deref(), Some("admin-pw"));
    }

    /// A malformed file must be a clear error, never a silent empty config —
    /// silently ignoring a typo would connect to the wrong server.
    #[test]
    fn rejects_malformed_toml() {
        let err = parse("[database\nhost = ").expect_err("should not parse");
        assert!(matches!(err, ConfigError::Parse(_)));
    }

    /// An unknown key is a typo, and typos in a config file that selects a
    /// database must not pass silently.
    #[test]
    fn rejects_unknown_keys() {
        let err = parse("[database]\nhsot = \"typo\"\n").expect_err("should not parse");
        assert!(matches!(err, ConfigError::Parse(_)));
    }

    /// `{:?}` on the config must never print the master key or a password. A
    /// panic message or a stray log line is the classic way secrets escape.
    #[test]
    fn debug_output_redacts_every_secret() {
        let cfg = parse(
            "[oms]\npassword = \"role-pw\"\nmaster_key = \"base64:KEYKEYKEY\"\n\
             [server]\nadmin_password = \"admin-pw\"\n",
        )
        .expect("parse");
        let rendered = format!("{cfg:?}");
        for secret in ["role-pw", "base64:KEYKEYKEY", "admin-pw"] {
            assert!(!rendered.contains(secret), "{secret} leaked into {rendered}");
        }
    }
}
