//! The `oms.toml` bootstrap file.
//!
//! Holds the settings that cannot live in the database, because they are what
//! tells the process how to reach it — plus the master key, which must not live
//! in the thing it encrypts. Everything else belongs in Postgres and is managed
//! from the cockpit.
//!
//! Every field is optional. The file is one tier in the flag → env → file →
//! default chain, so a half-filled file is normal rather than an error.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

/// Where the file lives when `OMS_CONFIG` says nothing. There is no `--config`
/// flag — only the environment variable.
pub const DEFAULT_FILENAME: &str = "oms.toml";

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FileConfig {
    #[serde(default)]
    pub database: DatabaseSection,
    #[serde(default)]
    pub oms: OmsSection,
    #[serde(default)]
    pub server: ServerSection,
    #[serde(default)]
    pub auth: AuthSection,
}

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct DatabaseSection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port: Option<u16>,
    /// Superuser *name* only. Its password is prompted, never stored — that
    /// credential can drop the database.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub database: Option<String>,
}

#[derive(Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct OmsSection {
    /// Password for the `oms` role the server connects as. Generated by `oms init`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// `base64:`-prefixed 32 bytes. Losing this loses every stored credential.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub master_key: Option<String>,
}

#[derive(Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ServerSection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bind_addr: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub admin_password: Option<String>,
}

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AuthSection {
    #[serde(default)]
    pub oidc: OidcSection,
}

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct OidcSection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_base_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub required_claim: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub required_claim_value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idle_ttl_minutes: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub absolute_ttl_hours: Option<i64>,
}

#[derive(Debug)]
pub struct OidcSettings {
    pub issuer: String,
    pub client_id: String,
    pub public_base_url: String,
    pub scopes: Vec<String>,
    pub required_claim: Option<(String, String)>,
    pub ttl: crate::sessions::SessionTtl,
}

// Hand-written so a stray `{:?}` — in a log line, a panic message, an
// `expect_err` — cannot print the master key or either password. `FileConfig`
// derives Debug and contains these, so deriving here would leak through it.
impl std::fmt::Debug for OmsSection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OmsSection")
            .field("password", &self.password.as_ref().map(|_| "<redacted>"))
            .field("master_key", &self.master_key.as_ref().map(|_| "<redacted>"))
            .finish()
    }
}

impl std::fmt::Debug for ServerSection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ServerSection")
            .field("bind_addr", &self.bind_addr)
            .field("admin_password", &self.admin_password.as_ref().map(|_| "<redacted>"))
            .finish()
    }
}

#[derive(Debug)]
pub enum ConfigError {
    Parse(String),
    Io(String),
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::Parse(m) => write!(f, "{m}"),
            ConfigError::Io(m) => write!(f, "{m}"),
        }
    }
}

impl std::error::Error for ConfigError {}

pub fn parse(toml_str: &str) -> Result<FileConfig, ConfigError> {
    toml::from_str(toml_str).map_err(|e| {
        // Deliberately NOT `e.to_string()`: the toml crate renders the offending
        // source line, which prints the secret when the error lands on a password
        // or the master key. Message plus location is enough to fix a typo.
        match e.span() {
            Some(s) => ConfigError::Parse(format!("{} (at bytes {}..{})", e.message(), s.start, s.end)),
            None => ConfigError::Parse(e.message().to_string()),
        }
    })
}

/// The configured path: `OMS_CONFIG` if set, else `DEFAULT_FILENAME` in the
/// current directory. This is the only way to relocate the file — there is no
/// `--config` flag.
pub fn path() -> PathBuf {
    std::env::var("OMS_CONFIG")
        .ok()
        .filter(|v| !v.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(DEFAULT_FILENAME))
}

/// Absolute form of `path()`, for messages that might be read after the process
/// working directory has changed (a systemd unit, a different terminal tab) — a
/// bare relative path in an error message gives no way to tell which `oms.toml`
/// was actually searched for. Falls back to the relative path if the CWD cannot
/// be read, which beats failing the message entirely over it.
pub fn path_abs() -> PathBuf {
    let p = path();
    if p.is_absolute() {
        return p;
    }
    std::env::current_dir().map(|cwd| cwd.join(&p)).unwrap_or(p)
}

static LOADED: OnceLock<Option<FileConfig>> = OnceLock::new();

/// Read and cache the file. Absent is `None` — running without one is valid.
///
/// A file that exists but does not parse is fatal: it means the operator wrote
/// something they believe is in effect. Silently ignoring it could point the
/// server at a different database than they intended. Same for any other read
/// failure (e.g. permission denied) on a file that does exist — it may hold the
/// master key, so falling back to defaults silently is not an option.
pub fn load() -> Option<&'static FileConfig> {
    LOADED
        .get_or_init(|| {
            let p = path();
            match std::fs::read_to_string(&p) {
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
                Err(e) => {
                    eprintln!("error: cannot read {}: {e}", p.display());
                    std::process::exit(1);
                }
                Ok(text) => match parse(&text) {
                    Ok(cfg) => Some(cfg),
                    Err(e) => {
                        eprintln!("error: {} is not valid: {e}", p.display());
                        std::process::exit(1);
                    }
                },
            }
        })
        .as_ref()
}

impl FileConfig {
    /// The OIDC settings, or `None` when login is not configured.
    ///
    /// Incomplete is treated as absent on purpose: a half-filled block would
    /// otherwise produce a login flow that cannot complete, and a 404 is a far
    /// clearer signal than a redirect into a broken exchange.
    pub fn oidc(&self) -> Option<OidcSettings> {
        let s = &self.auth.oidc;
        let (issuer, client_id, public_base_url) =
            (s.issuer.clone()?, s.client_id.clone()?, s.public_base_url.clone()?);

        Some(OidcSettings {
            issuer,
            client_id,
            public_base_url,
            scopes: s.scopes.clone().unwrap_or_else(|| {
                vec!["openid".into(), "profile".into(), "email".into()]
            }),
            required_claim: s
                .required_claim
                .clone()
                .zip(s.required_claim_value.clone()),
            ttl: crate::sessions::SessionTtl {
                idle: chrono::Duration::minutes(s.idle_ttl_minutes.unwrap_or(30)),
                absolute: chrono::Duration::hours(s.absolute_ttl_hours.unwrap_or(12)),
            },
        })
    }
}

/// Write a new config file, refusing to overwrite one that exists.
///
/// Created with mode 0600 *at open time* rather than chmod-ed afterwards, so
/// there is no window in which the master key sits in a world-readable file.
pub fn write_new(path: &Path, cfg: &FileConfig) -> Result<(), ConfigError> {
    use std::io::Write;
    use std::os::unix::fs::OpenOptionsExt;

    let body = toml::to_string_pretty(cfg).map_err(|e| ConfigError::Parse(e.to_string()))?;
    let header = "# openoms bootstrap configuration.\n\
                  #\n\
                  # Generated by `oms init`. Back this file up: the master key below is the\n\
                  # only thing that can decrypt stored broker credentials.\n\n";

    // create_new fails if the path exists — the check and the create are one
    // atomic operation, so a concurrent `oms init` cannot slip between them.
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)
        .map_err(|e| ConfigError::Io(format!("could not create {}: {e}", path.display())))?;

    // A failed write must not leave a comment-only file behind: that parses as
    // valid empty TOML, so the master key would vanish silently, and create_new
    // would then refuse the retry. Remove what we made and report the failure.
    if let Err(e) = f.write_all(header.as_bytes()).and_then(|_| f.write_all(body.as_bytes())) {
        let _ = std::fs::remove_file(path);
        return Err(ConfigError::Io(format!("could not write {}: {e}", path.display())));
    }
    Ok(())
}

/// The master key, on the usual env-over-file tiers.
///
/// Three-way return on purpose. `None` means no key is configured, which is
/// normal for an install that has never stored a credential. `Some(Err(_))` means
/// one was configured and is unusable — a typo must never be mistaken for
/// "absent", because absent is survivable and a wrong key is not.
pub fn master_key(
    file: Option<&FileConfig>,
) -> Option<Result<crate::secrets::MasterKey, crate::secrets::SecretError>> {
    std::env::var("OMS_MASTER_KEY")
        .ok()
        .filter(|v| !v.is_empty())
        .or_else(|| file.and_then(|f| f.oms.master_key.clone()))
        .filter(|v| !v.is_empty())
        .map(|raw| crate::secrets::parse_master_key(&raw))
}

#[cfg(test)]
mod tests {
    use super::*;

    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// Every field is optional: a partial file must parse, because the missing
    /// pieces fall through to env or the built-in defaults.
    #[test]
    fn parses_a_partial_file() {
        let cfg = parse("[database]\nhost = \"db.internal\"\n").expect("parse");
        assert_eq!(cfg.database.host.as_deref(), Some("db.internal"));
        assert_eq!(cfg.database.port, None);
        assert_eq!(cfg.oms.password, None);
    }

    /// An entirely empty file is legal and yields all-None.
    #[test]
    fn parses_an_empty_file() {
        let cfg = parse("").expect("parse");
        assert_eq!(cfg.database.host, None);
        assert_eq!(cfg.server.bind_addr, None);
    }

    #[test]
    fn parses_a_full_file() {
        let cfg = parse(
            r#"
[database]
host = "localhost"
port = 5432
username = "postgres"
database = "ods"

[oms]
password = "role-pw"
master_key = "base64:AAAA"

[server]
bind_addr = "0.0.0.0:3001"
admin_password = "admin-pw"
"#,
        )
        .expect("parse");
        assert_eq!(cfg.database.port, Some(5432));
        assert_eq!(cfg.oms.master_key.as_deref(), Some("base64:AAAA"));
        assert_eq!(cfg.server.bind_addr.as_deref(), Some("0.0.0.0:3001"));
        assert_eq!(cfg.server.admin_password.as_deref(), Some("admin-pw"));
    }

    /// A malformed file must be a clear error, never a silent empty config —
    /// silently ignoring a typo would connect to the wrong server.
    #[test]
    fn rejects_malformed_toml() {
        let err = parse("[database\nhost = ").expect_err("should not parse");
        assert!(matches!(err, ConfigError::Parse(_)));
    }

    /// An unknown key is a typo, and typos in a config file that selects a
    /// database must not pass silently.
    #[test]
    fn rejects_unknown_keys() {
        let err = parse("[database]\nhsot = \"typo\"\n").expect_err("should not parse");
        assert!(matches!(err, ConfigError::Parse(_)));
    }

    /// `{:?}` on the config must never print the master key or a password. A
    /// panic message or a stray log line is the classic way secrets escape.
    #[test]
    fn debug_output_redacts_every_secret() {
        let cfg = parse(
            "[oms]\npassword = \"role-pw\"\nmaster_key = \"base64:KEYKEYKEY\"\n\
             [server]\nadmin_password = \"admin-pw\"\n",
        )
        .expect("parse");
        let rendered = format!("{cfg:?}");
        for secret in ["role-pw", "base64:KEYKEYKEY", "admin-pw"] {
            assert!(!rendered.contains(secret), "{secret} leaked into {rendered}");
        }
    }

    /// A syntax error on the line carrying a secret must not echo that secret
    /// back in the error string — `toml::de::Error`'s `Display` renders the
    /// offending source line, so `parse` must build the message from
    /// `.message()`/`.span()` only, never `.to_string()`.
    #[test]
    fn parse_error_does_not_echo_a_broken_secret_line() {
        let err = parse("[oms]\nmaster_key = \"base64:SUPERSECRETKEY\n")
            .expect_err("should not parse");
        let rendered = err.to_string();
        assert!(!rendered.contains("SUPERSECRETKEY"), "leaked into {rendered}");
        assert!(!rendered.contains("base64:SUPERSECRETKEY"), "leaked into {rendered}");
    }

    use std::os::unix::fs::PermissionsExt;

    fn temp_path(name: &str) -> std::path::PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!("oms-cfg-test-{}-{}", std::process::id(), name));
        p
    }

    /// The file holds a master key and a role password: group- and world-readable
    /// would leak both to every account on the machine.
    #[test]
    fn writes_with_owner_only_permissions() {
        let p = temp_path("perms.toml");
        let _ = std::fs::remove_file(&p);
        write_new(&p, &FileConfig::default()).expect("write");

        let mode = std::fs::metadata(&p).expect("stat").permissions().mode();
        assert_eq!(mode & 0o777, 0o600, "mode was {:o}", mode & 0o777);
        std::fs::remove_file(&p).ok();
    }

    /// An all-None config serializes and deserializes correctly. The
    /// skip_serializing_if = "Option::is_none" annotation means an empty config
    /// writes as just a comment header and produces valid empty TOML.
    #[test]
    fn an_empty_config_round_trips() {
        let p = temp_path("empty.toml");
        let _ = std::fs::remove_file(&p);

        write_new(&p, &FileConfig::default()).expect("write");

        let back = parse(&std::fs::read_to_string(&p).expect("read")).expect("parse");
        assert_eq!(back.database.host, None);
        assert_eq!(back.oms.master_key, None);
        assert_eq!(back.server.bind_addr, None);
        std::fs::remove_file(&p).ok();
    }

    /// Round-trip: what we write must be what we read back.
    #[test]
    fn written_file_parses_back_identically() {
        let p = temp_path("roundtrip.toml");
        let _ = std::fs::remove_file(&p);

        let mut cfg = FileConfig::default();
        cfg.database.host = Some("db.internal".into());
        cfg.database.port = Some(6543);
        cfg.oms.password = Some("role-pw".into());
        cfg.oms.master_key = Some("base64:AAAA".into());
        write_new(&p, &cfg).expect("write");

        let back = parse(&std::fs::read_to_string(&p).expect("read")).expect("parse");
        assert_eq!(back.database.host.as_deref(), Some("db.internal"));
        assert_eq!(back.database.port, Some(6543));
        assert_eq!(back.oms.password.as_deref(), Some("role-pw"));
        assert_eq!(back.oms.master_key.as_deref(), Some("base64:AAAA"));
        std::fs::remove_file(&p).ok();
    }

    /// Refuse to clobber. The existing file may hold the only copy of a master
    /// key, and overwriting it destroys every stored credential.
    #[test]
    fn refuses_to_overwrite_an_existing_file() {
        let p = temp_path("exists.toml");
        std::fs::write(&p, "# already here\n").expect("seed");

        let err = write_new(&p, &FileConfig::default()).expect_err("must refuse");
        assert!(matches!(err, ConfigError::Io(_)));
        assert_eq!(std::fs::read_to_string(&p).expect("read"), "# already here\n");
        std::fs::remove_file(&p).ok();
    }

    use crate::secrets::{open, seal};

    const ENV_KEY: &str = "base64:AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=";
    const FILE_KEY: &str = "base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

    /// Seals a probe under `resolved` and checks it opens under `expected` — the only
    /// way to assert which key won without weakening MasterKey's redaction.
    fn resolved_is(resolved: &crate::secrets::MasterKey, expected: &str) -> bool {
        let expected = crate::secrets::parse_master_key(expected).expect("fixture key");
        let sealed = seal(resolved, "probe", b"x");
        open(&expected, "probe", &sealed).map(|p| p == b"x").unwrap_or(false)
    }

    /// The key follows the same env-over-file precedence as everything else, so a
    /// container can inject it without shipping a config file.
    #[test]
    fn master_key_prefers_env_then_file() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());

        // File key wins when env is unset.
        let file = parse(
            "[oms]\nmaster_key = \"base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\"\n",
        )
        .expect("parse");
        let result_file_only = master_key(Some(&file)).expect("configured").expect("valid");
        std::env::remove_var("OMS_MASTER_KEY");
        assert!(resolved_is(&result_file_only, FILE_KEY), "file key should win when env unset");

        // Env key wins when both are set.
        std::env::set_var("OMS_MASTER_KEY", ENV_KEY);
        let result_both = master_key(Some(&file)).expect("configured").expect("valid");
        std::env::remove_var("OMS_MASTER_KEY");
        assert!(resolved_is(&result_both, ENV_KEY), "env key should win when both present");
    }

    /// Empty env variable falls through to the file key.
    #[test]
    fn master_key_empty_env_falls_back_to_file() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());

        let file = parse(
            "[oms]\nmaster_key = \"base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\"\n",
        )
        .expect("parse");
        std::env::set_var("OMS_MASTER_KEY", "");
        let result = master_key(Some(&file)).expect("configured").expect("valid");
        std::env::remove_var("OMS_MASTER_KEY");
        assert!(resolved_is(&result, FILE_KEY), "empty env should fall back to file");
    }

    /// Invalid env key with valid file key produces an error, never silently falling back.
    #[test]
    fn master_key_invalid_env_does_not_fall_back_to_file() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());

        let file = parse(
            "[oms]\nmaster_key = \"base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\"\n",
        )
        .expect("parse");
        std::env::set_var("OMS_MASTER_KEY", "base64:INVALID");
        let result = master_key(Some(&file)).expect("configured");
        std::env::remove_var("OMS_MASTER_KEY");
        assert!(result.is_err(), "invalid env should error, not fall back to file");
    }

    /// Nothing configured is not an error — an install with no credentials yet is
    /// perfectly valid. The caller decides whether that is fatal.
    #[test]
    fn master_key_absent_is_none_not_an_error() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::remove_var("OMS_MASTER_KEY");
        let result_none = master_key(None);
        let result_default = master_key(Some(&FileConfig::default()));
        std::env::remove_var("OMS_MASTER_KEY");
        assert!(result_none.is_none());
        assert!(result_default.is_none());
    }

    /// A configured but unusable key must surface as an error, never as "absent" —
    /// silently treating a typo'd key as "no credentials" would look like data loss.
    #[test]
    fn master_key_present_but_invalid_is_an_error() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let file = parse("[oms]\nmaster_key = \"base64:AAAA\"\n").expect("parse");
        let result = master_key(Some(&file)).expect("configured");
        std::env::remove_var("OMS_MASTER_KEY");
        assert!(result.is_err());
    }

    #[test]
    fn no_oidc_block_means_no_oidc() {
        let cfg: FileConfig = toml::from_str("[server]\nbind_addr = \"localhost:3001\"\n").unwrap();

        assert!(cfg.oidc().is_none(), "absent configuration must not half-enable login");
    }

    #[test]
    fn a_complete_block_produces_settings_with_defaults_filled_in() {
        let cfg: FileConfig = toml::from_str(
            r#"
            [auth.oidc]
            issuer = "https://id.example.com"
            client_id = "oms"
            public_base_url = "https://oms.example.com"
            "#,
        )
        .unwrap();

        let settings = cfg.oidc().expect("settings");
        assert_eq!(settings.issuer, "https://id.example.com");
        assert_eq!(settings.scopes, vec!["openid", "profile", "email"]);
        assert_eq!(settings.ttl.idle, chrono::Duration::minutes(30));
        assert_eq!(settings.ttl.absolute, chrono::Duration::hours(12));
        assert!(settings.required_claim.is_none());
    }

    #[test]
    fn an_incomplete_block_is_refused_rather_than_half_applied() {
        let cfg: FileConfig = toml::from_str(
            "[auth.oidc]\nissuer = \"https://id.example.com\"\n",
        )
        .unwrap();

        assert!(cfg.oidc().is_none(), "issuer without client_id cannot log anyone in");
    }

    #[test]
    fn missing_client_id_is_caught() {
        let cfg: FileConfig = toml::from_str(
            r#"
            [auth.oidc]
            issuer = "https://id.example.com"
            public_base_url = "https://oms.example.com"
            "#,
        )
        .unwrap();

        assert!(cfg.oidc().is_none(), "missing client_id must refuse the config");
    }

    #[test]
    fn missing_public_base_url_is_caught() {
        let cfg: FileConfig = toml::from_str(
            r#"
            [auth.oidc]
            issuer = "https://id.example.com"
            client_id = "oms"
            "#,
        )
        .unwrap();

        assert!(cfg.oidc().is_none(), "missing public_base_url must refuse the config");
    }

    #[test]
    fn a_claim_gate_needs_both_halves_to_bind() {
        let cfg: FileConfig = toml::from_str(
            r#"
            [auth.oidc]
            issuer = "https://id.example.com"
            client_id = "oms"
            public_base_url = "https://oms.example.com"
            required_claim = "groups"
            required_claim_value = "traders"
            "#,
        )
        .unwrap();

        let settings = cfg.oidc().expect("settings");
        assert_eq!(settings.required_claim, Some(("groups".into(), "traders".into())));
    }

    #[test]
    fn claim_gate_without_value_does_not_bind() {
        let cfg: FileConfig = toml::from_str(
            r#"
            [auth.oidc]
            issuer = "https://id.example.com"
            client_id = "oms"
            public_base_url = "https://oms.example.com"
            required_claim = "groups"
            "#,
        )
        .unwrap();

        let settings = cfg.oidc().expect("settings");
        assert!(settings.required_claim.is_none(), "claim gate needs both claim and value");
    }

    #[test]
    fn claim_gate_without_claim_does_not_bind() {
        let cfg: FileConfig = toml::from_str(
            r#"
            [auth.oidc]
            issuer = "https://id.example.com"
            client_id = "oms"
            public_base_url = "https://oms.example.com"
            required_claim_value = "traders"
            "#,
        )
        .unwrap();

        let settings = cfg.oidc().expect("settings");
        assert!(settings.required_claim.is_none(), "claim gate needs both claim and value");
    }

    #[test]
    fn ttls_are_overridable() {
        let cfg: FileConfig = toml::from_str(
            r#"
            [auth.oidc]
            issuer = "https://id.example.com"
            client_id = "oms"
            public_base_url = "https://oms.example.com"
            idle_ttl_minutes = 15
            absolute_ttl_hours = 8
            "#,
        )
        .unwrap();

        let settings = cfg.oidc().expect("settings");
        assert_eq!(settings.ttl.idle, chrono::Duration::minutes(15));
        assert_eq!(settings.ttl.absolute, chrono::Duration::hours(8));
    }
}
